# Generated by Django 4.2.30 on 2026-05-06 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('births', models.IntegerField()),
                ('deaths', models.IntegerField()),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='YearlyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('births', models.IntegerField()),
                ('deaths', models.IntegerField()),
                ('clinic', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['clinic', 'year'],
            },
        ),
    ]
